lang: en-US
title: underlog
author: adri0

base_url: /
url: http://adri0.com
enforce_ssl: https://adri0.com

twitter_username: adri0__
github_username: adri0

logo: /assets/images/nu.png

remote_theme: "adri0/jekyll-theme-basically-basic"

permalink: /:title

markdown: kramdown

liquid:
  error_mode: strict

plugins:
  - jekyll-sitemap 
  - jekyll-feed 
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - old