lang: en
title: adri0
author: adri0

base_url: /
url: http://adri0.com
enforce_ssl: https://adri0.com

twitter_username: adri0__
github_username: adri0

remote_theme: "adri0/no-style-please"

theme_config:
  appearance: "auto"
  back_home_text: "home"
  date_format: "%Y-%m-%d"
  show_description: true

markdown: kramdown

permalink: /blog/:title

liquid:
  error_mode: strict

plugins:
  - jekyll-sitemap 
  - jekyll-feed 
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - old